### ISSUE TITLE
The morpheus-cloud-plugin does not load on Morpheus 5.2.3-2

### ISSUE THREAD

**Issue by robertoafilho** [gomorpheus/morpheus-plugin-core#14]
Hi, 

I am trying to load the morpheus-cloud-plugin sample (built on the master branch) into my appliance (version 5.2.3-2) and it fails with the error below (/var/log/morpheus/morpheus-ui/current). I noticed that my instance uses the morpheus-plugin-api version 
 0.6.0. So, is there a way of running the cloud plugin sample on my appliance? 

Thank you!

`2021-02-19_23:20:46.11439 org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/morpheusdata/model/Cloud
2021-02-19_23:20:46.11440 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
2021-02-19_23:20:46.11440 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
2021-02-19_23:20:46.11440 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
2021-02-19_23:20:46.11440 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
2021-02-19_23:20:46.11441 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
2021-02-19_23:20:46.11441 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
2021-02-19_23:20:46.11441 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
2021-02-19_23:20:46.11441 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
2021-02-19_23:20:46.11441 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11442 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2021-02-19_23:20:46.11442 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11443 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11443 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
2021-02-19_23:20:46.11443 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11444 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11444 	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
2021-02-19_23:20:46.11444 	at com.morpheus.remote.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:20)
2021-02-19_23:20:46.11444 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11444 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11445 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11448 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
2021-02-19_23:20:46.11448 	at org.springframework.security.web.authentication.switchuser.SwitchUserFilter.doFilter(SwitchUserFilter.java:200)
2021-02-19_23:20:46.11449 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11450 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
2021-02-19_23:20:46.11450 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
2021-02-19_23:20:46.11450 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11450 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
2021-02-19_23:20:46.11450 	at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
2021-02-19_23:20:46.11451 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11451 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2021-02-19_23:20:46.11452 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11452 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11452 	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
2021-02-19_23:20:46.11452 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11452 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
2021-02-19_23:20:46.11453 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11454 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
2021-02-19_23:20:46.11455 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11455 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
2021-02-19_23:20:46.11456 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11456 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11456 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
2021-02-19_23:20:46.11456 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11456 	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
2021-02-19_23:20:46.11457 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11457 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
2021-02-19_23:20:46.11458 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11458 	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
2021-02-19_23:20:46.11458 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11458 	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:124)
2021-02-19_23:20:46.11459 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11459 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
2021-02-19_23:20:46.11459 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
2021-02-19_23:20:46.11459 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
2021-02-19_23:20:46.11459 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11460 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11460 	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
2021-02-19_23:20:46.11461 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11461 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11461 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11461 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2021-02-19_23:20:46.11461 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11462 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11462 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11462 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
2021-02-19_23:20:46.11462 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
2021-02-19_23:20:46.11463 	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
2021-02-19_23:20:46.11464 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11464 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
2021-02-19_23:20:46.11464 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11464 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11464 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
2021-02-19_23:20:46.11465 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2021-02-19_23:20:46.11465 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19_23:20:46.11468 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19_23:20:46.11468 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
2021-02-19_23:20:46.11468 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2021-02-19_23:20:46.11469 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
2021-02-19_23:20:46.11469 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
2021-02-19_23:20:46.11469 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2021-02-19_23:20:46.11469 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
2021-02-19_23:20:46.11469 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2021-02-19_23:20:46.11470 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
2021-02-19_23:20:46.11470 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
2021-02-19_23:20:46.11470 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2021-02-19_23:20:46.11470 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
2021-02-19_23:20:46.11470 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
2021-02-19_23:20:46.11470 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2021-02-19_23:20:46.11470 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-02-19_23:20:46.11471 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-02-19_23:20:46.11471 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2021-02-19_23:20:46.11471 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by davydotcom** [comment]
The cloud plug-in is a work in progress plug-in provider type and is
marked as coming soon on the developer portal. It is not yet released 


On February 19, 2021, GitHub <notifications@github.com> wrote:
> Hi,
>
> I am trying to load the morpheus-cloud-plugin sample (built on the
> master branch) into my appliance (version 5.2.3-2) and it fails with

> the error below (/var/log/morpheus/morpheus-ui/current). I noticed
> that my instance uses the morpheus-plugin-api version
>  0.6.0. So, is there a way of running the cloud plugin sample on my
> appliance?
>
> Thank you!
>
> 2021-02-19_23:20:46.11439
> org.springframework.web.util.NestedServletException: Handler dispatch

> failed; nested exception is java.lang.NoClassDefFoundError:
> com/morpheusdata/model/Cloud 2021-02-19_23:20:46.11440 at
> org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
> 2021-02-19_23:20:46.11440 at
> org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
> 2021-02-19_23:20:46.11440 at
> org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
> 2021-02-19_23:20:46.11440 at
> org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
> 2021-02-19_23:20:46.11441 at
> javax.servlet.http.HttpServlet.service(HttpServlet.java:652) 2021-02-

> 19_23:20:46.11441 at
> org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
> 2021-02-19_23:20:46.11441 at
> javax.servlet.http.HttpServlet.service(HttpServlet.java:733) 2021-02-

> 19_23:20:46.11441 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 2021-02-19_23:20:46.11441 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11442 at
> org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

> 2021-02-19_23:20:46.11442 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11443 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11443 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
> 2021-02-19_23:20:46.11443 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11444 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11444 at
> org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
> 2021-02-19_23:20:46.11444 at
> com.morpheus.remote.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:20)
> 2021-02-19_23:20:46.11444 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11444 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11445 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11448 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
> 2021-02-19_23:20:46.11448 at
> org.springframework.security.web.authentication.switchuser.SwitchUserFilter.doFilter(SwitchUserFilter.java:200)
> 2021-02-19_23:20:46.11449 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11450 at
> org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
> 2021-02-19_23:20:46.11450 at
> org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
> 2021-02-19_23:20:46.11450 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11450 at
> org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
> 2021-02-19_23:20:46.11450 at
> grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
> 2021-02-19_23:20:46.11451 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11451 at
> org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
> 2021-02-19_23:20:46.11452 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11452 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11452 at
> grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
> 2021-02-19_23:20:46.11452 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11452 at
> org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
> 2021-02-19_23:20:46.11453 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11454 at
> org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)

> 2021-02-19_23:20:46.11455 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11455 at
> org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
> 2021-02-19_23:20:46.11456 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11456 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11456 at
> org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
> 2021-02-19_23:20:46.11456 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11456 at
> grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
> 2021-02-19_23:20:46.11457 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11457 at
> org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
> 2021-02-19_23:20:46.11458 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11458 at
> grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
> 2021-02-19_23:20:46.11458 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11458 at
> org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:124)
> 2021-02-19_23:20:46.11459 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11459 at
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 2021-02-19_23:20:46.11459 at
> org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
> 2021-02-19_23:20:46.11459 at
> org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
> 2021-02-19_23:20:46.11459 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11460 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11460 at
> org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
> 2021-02-19_23:20:46.11461 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11461 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11461 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11461 at
> org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
> 2021-02-19_23:20:46.11461 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11462 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11462 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11462 at
> org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
> 2021-02-19_23:20:46.11462 at
> org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
> 2021-02-19_23:20:46.11463 at
> org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
> 2021-02-19_23:20:46.11464 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11464 at
> org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
> 2021-02-19_23:20:46.11464 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11464 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11464 at
> org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
> 2021-02-19_23:20:46.11465 at
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
> 2021-02-19_23:20:46.11465 at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 2021-02-19_23:20:46.11468 at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 2021-02-19_23:20:46.11468 at
> org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
> 2021-02-19_23:20:46.11468 at
> org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 2021-02-19_23:20:46.11469 at
> org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
> 2021-02-19_23:20:46.11469 at
> org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
> 2021-02-19_23:20:46.11469 at
> org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 2021-02-19_23:20:46.11469 at
> org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
> 2021-02-19_23:20:46.11469 at
> org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 2021-02-19_23:20:46.11470 at
> org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 2021-02-19_23:20:46.11470 at
> org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
> 2021-02-19_23:20:46.11470 at
> org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 2021-02-19_23:20:46.11470 at
> org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
> 2021-02-19_23:20:46.11470 at
> org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
> 2021-02-19_23:20:46.11470 at
> org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 2021-02-19_23:20:46.11470 at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 2021-02-19_23:20:46.11471 at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 2021-02-19_23:20:46.11471 at
> org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 2021-02-19_23:20:46.11471 at java.lang.Thread.run(Thread.java:748) 
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gomorpheus/morpheus-plugin-core/issues/14>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAAFUESPLCHTHJ4GJM2VQPTS73XUHANCNFSM4X5GF4DQ>.

**Comment by robertofilho-ctl** [comment]
Thanks for the replay @davydotcom. I saw that the pull request that introduced the cloud sample passed the CI checks, and I thought it was ready to go. Do you guys have an approximate date of release of that feature? Thank you!

**Comment by robertoafilho** [comment]
Thanks for the replay @davydotcom. I saw that the pull request that introduced the cloud sample passed the CI checks, and I thought it was ready to go. Do you guys have an approximate date of release of that feature? Thank you!
